### ISSUE TITLE
运行后core报错 无限重启

### ISSUE THREAD

**Issue by Himeno-Yumemi** [rhwong/qsign-onekey#57]
```
Qsign API:http://127.0.0.1:13579
KEY=1145141919810
Qsign_version:2023-12-19
TXlib_version:8.9.90
--------------------------------------------------------------------------------
-----------------
Check if the curl command is installed in the environment variables...
The curl command is not detected, use the "curl.exe" from the lib folder.This pr
ecompiled executable works only on x86 architecture systems.
Qsign API is not running, Restarting...
Qsign API running on processes with PID:1428.
Qsign API is not running, Restarting...
Qsign API running on processes with PID:1428.
Qsign API is not running, Restarting...
Qsign API running on processes with PID:1428.
Qsign API is not running, Restarting...
Qsign API running on processes with PID:1428.
Qsign API is not running, Restarting...
```
```
Qsign API running on processes with PID:1428.
Qsign API is not running, Restarting...
```
这两条是同时出现的 运行的同时判断未启动导致的重启?

**core的报错:**
我也不知道哪个端口被占用了
```
Exception in thread "main" java.net.BindException: Address already in use: bind
       at java.base/sun.nio.ch.Net.bind0(Native Method)
       at java.base/sun.nio.ch.Net.bind(Unknown Source)
       at java.base/sun.nio.ch.Net.bind(Unknown Source)
       at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(Unknown Source)
       at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSo
ketChannel.java:141)
       at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.
ava:562)
       at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChann
lPipeline.java:1334)
       at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractCha
nelHandlerContext.java:600)
       at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHa
dlerContext.java:579)
       at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.j
va:973)
       at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
       at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356

       at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventE
ecutor.java:174)
       at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEv
ntExecutor.java:167)
       at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(Single
hreadEventExecutor.java:470)
       at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
       at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThread
ventExecutor.java:997)
       at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java
74)
       at io.ktor.server.netty.EventLoopGroupProxy$Companion.create$lambda$1$la
bda$0(NettyApplicationEngine.kt:296)
       at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalR
nnable.java:30)
       at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by rhwong** [comment]
你猜是哪个端口被占用了？？？
如果你服务器上有第二个及以上的qsign，请自行更换后续qsign所使用的的端口，计算机不允许你两个程序使用同一个端口

**Comment by rhwong** [comment]
这也报bug我是服的

**Comment by rhwong** [comment]
监控窗口只监控，他没有占用端口。

**Comment by rhwong** [comment]
> 解决了 跟#46 一样的问题 安装curl就没问题了 我2012r2是用的64位系统 自带的32位用不了

可是x86_64是兼容的x86的
